# See: https://docs.docker.com/compose/compose-file/compose-file-v2/
version: '2.3'

volumes:

  master_data:

networks:

  lan:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/16
          gateway: 10.0.0.1

services:

  master:
    container_name: demo_master
    image: conreality/master:latest
    build: https://github.com/conreality/conreality-master.git
    volumes:
      - master_data:/srv
    networks:
      lan:
        ipv4_address: 10.0.1.1
    ports:
      - '5432:5432'
    command: postgres

  slave:
    image: conreality/slave:latest
    build: https://github.com/conreality/conreality-slave.git
    networks:
      lan:
        ipv4_address: 10.0.1.2
    depends_on:
      - master
    command: ping master
